plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xcheng.xclogger'
    compileSdk 33

    defaultConfig {
        applicationId "com.xcheng.xclogger"
        minSdk 29
        targetSdk 33
        versionCode 1
        versionName "1.1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // 启用混淆与资源压缩
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        def baseName = "XCLogger"
        def buildType = variant.buildType.name
        def versionName = variant.versionName ?: "V1.0.0"
        def versionCode = variant.versionCode ?: 1
        def timestamp = new Date().format("yyyyMMddHHmm")
        def apkName

        if (buildType == "debug") {
            apkName = "${baseName}_v${versionName}_${timestamp}.apk"
        } else {
            apkName = "${baseName}_v${versionName}_${timestamp}.apk"
        }

        apkName = apkName.replaceAll("[^a-zA-Z0-9_.-]", "_")

        variant.outputs.each { output ->
            output.outputFileName = apkName
        }
    }
    buildFeatures {
        aidl true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}